import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'


import "./globals.css";
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="light scroll-smooth">
        <body
          className={cn(
            'min-h-screen font-sans antialiased grainy',
            inter.className
          )}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}